name: pontibus
channels:
  - conda-forge
dependencies:
  - pip
  - openfe
  #Testing deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - mypy
  - nbval
  # docs
  - pip:
    - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@a45f3edd5bc3e973c1a01b577c71efa1b62a65d6
