name: pontibus
channels:
  - conda-forge
dependencies:
  - pip
  - openfe
  - openff-toolkit >0.16.0
  - openff-interchange >0.3.28
  #Testing deps
  - pytest
  - pytest-cov
  - pytest-xdist
  - mypy
  - nbval
  # docs
  - pip:
    - git+https://github.com/OpenFreeEnergy/ofe-sphinx-theme@a45f3edd5bc3e973c1a01b577c71efa1b62a65d6
